apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: desk-booking-prod
  region: ap-southeast-2

vpc:
  id: vpc-04800afbd81581705
  subnets:
    public:
      ap-southeast-2a: { id: subnet-040e03ebf6c89f0c9 }
      ap-southeast-2b: { id: subnet-02104c2913ca5cf5f }
      ap-southeast-2c: { id: subnet-0cccdd8d50024c223 }

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 40
