version: '3.3'
services:
  db_migration:
    image: jimmyruann/desk_booking_prisma_migration
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_INITIAL_PASSWORD: ${ADMIN_INITIAL_PASSWORD}

  app:
    image: jimmyruann/desk_booking_app
    environment:
      API_HOST: api
      API_PORT: '3333'
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    image: jimmyruann/desk_booking_api
    expose:
      - '3333'
    depends_on:
      - db_migration
    environment:
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DATABASE_URL: ${DATABASE_URL}
