version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  db_migration:
    image: desk_booking_prisma_migration
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres?schema=public

  app:
    image: desk_booking_app
    environment:
      API_HOST: api
      API_PORT: 3333
    ports:
      - '80:80'
    depends_on:
      - api
      - db_migration
      - db

  api:
    image: desk_booking_api
    ports:
      - '3333:3333'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_ACCESS_SECRET=example_access_secret
      - JWT_REFRESH_SECRET=example_refresh_secret
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?schema=public

volumes:
  database:
