version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - '5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  db_migration:
    image: desk_booking_prisma_migration
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      ADMIN_INITIAL_PASSWORD: ${ADMIN_INITIAL_PASSWORD}

  app:
    image: desk_booking_app
    environment:
      API_HOST: api
      API_PORT: '3333'
    ports:
      - '80:80'
    depends_on:
      - api
      - db_migration
      - db

  api:
    image: desk_booking_api
    expose:
      - '3333'
    depends_on:
      db:
        condition: service_healthy
    environment:
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public

volumes:
  database:
    external: true
