apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: jimmyruann/desk_booking_api:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
            - name: REDIS_URL
              value: redis://redis:6379
            - name: HCAPTCHA_SECRET
              value: $HCAPTCHA_SECRET
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jimmyruann/desk_booking_app:latest
          imagePullPolicy: Always
          env:
            - name: API_HOST
              value: api
            - name: API_PORT
              value: '3333'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          volumeMounts:
            - name: redis-pv-volume
      volumes:
        - name: redis-pv-volume
          hostPath:
            path: '/mnt/redis'
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-migration
  labels:
    app: db-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-migration
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      containers:
        - name: db-migration
          image: jimmyruann/desk_booking_prisma
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
            - name: ADMIN_INITIAL_PASSWORD
              value: $ADMIN_INITIAL_PASSWORD
            - name: APP_SESSION_SECRET
              value: $APP_SESSION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 3333
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
