apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: jimmyruann/desk_booking_api:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
            - name: REDIS_URL
              value: redis://redis:6379
            - name: HCAPTCHA_SECRET
              value: $HCAPTCHA_SECRET
            - name: APP_SESSION_SECRET
              value: $APP_SESSION_SECRET
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jimmyruann/desk_booking_app:latest
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-migration
  labels:
    app: db-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-migration
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      containers:
        - name: db-migration
          image: jimmyruann/desk_booking_prisma
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
            - name: ADMIN_INITIAL_PASSWORD
              value: $ADMIN_INITIAL_PASSWORD
            - name: APP_SESSION_SECRET
              value: $APP_SESSION_SECRET
            - name: REDIS_URL
              value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 3333
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-Proto: https";
      rewrite ^/api/(.*)$ /api/$1 break;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - desk-booking.localdev.me
      secretName: dev-local
  rules:
    - host: desk-booking.localdev.me
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3333
