apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 1
  template:
    spec:
      initContainers:
        - name: wait-for-pg
          image: postgres:14.2-alpine
          imagePullPolicy: IfNotPresent
          command:
            [
              'sh',
              '-c',
              'until nc -vz ${POD_NAME}.${POD_NAMESPACE} 5432; do echo "Waiting for postgres..."; sleep 3; done;',
            ]
          env:
            - name: POD_NAME
              value: db
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      containers:
        - name: db-migration
          image: jimmyruann/desk_booking_prisma_migration
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: $DATABASE_URL
            - name: ADMIN_INITIAL_PASSWORD
              value: $ADMIN_INITIAL_PASSWORD
      restartPolicy: Never
